drop database if exists hotelDB;
create database hotelDB;

INSERT INTO categories VALUES (1,"Descubre hoteles","HOTEL","https://digitalbookinggruposseis.s3.amazonaws.com/categories/hoteles.jpg");
INSERT INTO categories VALUES (2,"Descubre hostels","HOSTEL","https://digitalbookinggruposseis.s3.amazonaws.com/categories/hostels.jpg");
INSERT INTO categories VALUES (3,"Descubre departamentos","DEPARTAMENTO","https://digitalbookinggruposseis.s3.amazonaws.com/categories/departamentos.jpeg");
INSERT INTO categories VALUES (4,"Descubre beds & breakfast","BED AND BREAKFAST","https://digitalbookinggruposseis.s3.amazonaws.com/categories/bed-and-breakfast.jpg");
INSERT INTO cities VALUES (1,"Mendoza","Argentina");
INSERT INTO cities VALUES (2,"Buenos Aires","Argentina");
INSERT INTO cities VALUES (3,"Bogotá","Colombia");
INSERT INTO cities VALUES (4,"Medellín","Colombia");
INSERT INTO cities VALUES (5,"Bariloche","Argentina");
INSERT INTO characteristics VALUES (1,"FaWiFi","Wifi");
INSERT INTO characteristics VALUES (2,"FaSwim","Piscina");
INSERT INTO characteristics VALUES (3,"FaCoffee","Cafetería");
INSERT INTO characteristics VALUES (4,"FaUtensils","Restaurante");
INSERT INTO characteristics VALUES (5,"FaSnowflake","Aire acondicionado");
INSERT INTO characteristics VALUES (6,"FaSmokingBan","Prohibido fumar");
INSERT INTO characteristics VALUES (7,"FaTv","Televisor");
INSERT INTO characteristics VALUES (8,"FaCocktail","Bar");
INSERT INTO characteristics VALUES (9,"FaPaw","Apto mascotas");
INSERT INTO characteristics VALUES (10,"FaCar","Estacionamiento");
INSERT INTO characteristics VALUES (11,"FaConciergeBell","Servicio de habitación");
INSERT INTO characteristics VALUES (12,"FaDumbbell","Gimnasio");
INSERT INTO characteristics VALUES (13,"FaSpa","Spa");
INSERT INTO products VALUES (1,"Con su magnífica fachada neoclásica del siglo XX y rodeado por imponentes paisajes de viñedos bajo la Cordillera de los Andes, se convierte en un destino ideal para viajes de placer y negocios.","Park Hyatt Mendoza",1,1);
INSERT INTO products VALUES (2,"Ubicado en el corazón del distrito de negocios y recientemente remodelado, combina el estilo contemporáneo y vanguardista con la tradición atemporal. Se encuentra cerca del casco antiguo de Usaquén, convirtiéndolo en un lugar ideal para centrarse en los negocios y después relajarse.","NH Collection Royal",1,3);
INSERT INTO products VALUES (3,"Una casa reformada del siglo XIX que ofrece alojamiento económico, a solo 600 metros del Obelisco. Cuenta con cocina compartida y bar. Habitaciones amplias y luminosas con suelo de parquet y baño privado. Las habitaciones compartidas cuentan con baño compartido.","Milhouse Hostel Avenue",2,2);
INSERT INTO products VALUES (4,"Elegante y exclusivo. Ubicado en un exuberante valle tropical, es una mezcla perfecta de vida urbana y áreas verdes. Habitaciones privadas con diferentes configuraciones y dormitorios para 4, 6 y 8 personas, te garantizamos que encontrarás exactamente lo que buscas.","Hostal Los Patios",2,4);
INSERT INTO products VALUES (5,"Amplios espacios decorados con gran estilo, únicos por su privacidad, equipamiento y servicios de inmejorable calidad. Espectacular terraza en esquina que ofrece una vista privilegiada y un ambiente soñado para relajarse, descansar, trabajar o compartir reuniones con 
amigos.","Soho Point Suites",3,2);
INSERT INTO products VALUES (6,"Ubicado en el 13° piso de torre Bellini, un ambiente luminoso, con diseño y confort. Cama Queen, pequeño living y escritorio con vista a las cúpulas de Buenos Aires. Un lugar versátil tanto para descansar como para quien tenga que estar en la ciudad por actividades laborales.","Apart con balcón",3,2);
INSERT INTO products VALUES (7,"Situada a 4,3 km del centro de Bariloche, en una mansión de estilo alpino rodeada de un hermoso jardín. A 800 metros del Lago Nahuel Huapi, ofrece habitaciones acogedoras con decoración rústica, TV de pantalla plana y baño privado con ducha.","Hostería Del Prado",4,5);
INSERT INTO products VALUES (8,"Ubicado en el distrito de Monserrat, a pocos pasos del Palacio Barolo, cerca del Tortoni Cafe, el Obelisco y el teatro Colón. Variadas opciones gastronómicas y una excelente vida nocturna para disfrutar.","Avenida Tango",4,2);
INSERT INTO product_characteristic VALUES (1,1);
INSERT INTO product_characteristic VALUES (1,2);
INSERT INTO product_characteristic VALUES (1,4);
INSERT INTO product_characteristic VALUES (1,5);
INSERT INTO product_characteristic VALUES (1,8);
INSERT INTO product_characteristic VALUES (1,9);
INSERT INTO product_characteristic VALUES (1,10);
INSERT INTO product_characteristic VALUES (1,11);
INSERT INTO product_characteristic VALUES (1,12);
INSERT INTO product_characteristic VALUES (1,13);
INSERT INTO product_characteristic VALUES (2,1);
INSERT INTO product_characteristic VALUES (2,2);
INSERT INTO product_characteristic VALUES (2,3);
INSERT INTO product_characteristic VALUES (2,4);
INSERT INTO product_characteristic VALUES (2,5);
INSERT INTO product_characteristic VALUES (2,8);
INSERT INTO product_characteristic VALUES (2,10);
INSERT INTO product_characteristic VALUES (2,11);
INSERT INTO product_characteristic VALUES (2,12);
INSERT INTO product_characteristic VALUES (2,13);
INSERT INTO product_characteristic VALUES (3,1);
INSERT INTO product_characteristic VALUES (3,3);
INSERT INTO product_characteristic VALUES (3,4);
INSERT INTO product_characteristic VALUES (3,5);
INSERT INTO product_characteristic VALUES (3,6);
INSERT INTO product_characteristic VALUES (3,7);
INSERT INTO product_characteristic VALUES (3,8);
INSERT INTO product_characteristic VALUES (4,1);
INSERT INTO product_characteristic VALUES (4,3);
INSERT INTO product_characteristic VALUES (4,6);
INSERT INTO product_characteristic VALUES (4,7);
INSERT INTO product_characteristic VALUES (4,8);
INSERT INTO product_characteristic VALUES (5,1);
INSERT INTO product_characteristic VALUES (5,2);
INSERT INTO product_characteristic VALUES (5,5);
INSERT INTO product_characteristic VALUES (5,6);
INSERT INTO product_characteristic VALUES (5,7);
INSERT INTO product_characteristic VALUES (6,1);
INSERT INTO product_characteristic VALUES (6,2);
INSERT INTO product_characteristic VALUES (6,5);
INSERT INTO product_characteristic VALUES (6,6);
INSERT INTO product_characteristic VALUES (6,7);
INSERT INTO product_characteristic VALUES (6,12);
INSERT INTO product_characteristic VALUES (7,1);
INSERT INTO product_characteristic VALUES (7,5);
INSERT INTO product_characteristic VALUES (7,6);
INSERT INTO product_characteristic VALUES (7,7);
INSERT INTO product_characteristic VALUES (7,9);
INSERT INTO product_characteristic VALUES (7,10);
INSERT INTO product_characteristic VALUES (8,1);
INSERT INTO product_characteristic VALUES (8,5);
INSERT INTO product_characteristic VALUES (8,6);
INSERT INTO product_characteristic VALUES (8,7);
INSERT INTO product_characteristic VALUES (8,12);
INSERT INTO images VALUES (1,"Portada1","https://digitalbookinggruposseis.s3.amazonaws.com/products/product1/portada%2B.jpg",1);
INSERT INTO images VALUES (2,"img1prod1","https://digitalbookinggruposseis.s3.amazonaws.com/products/product1/img1prod1.webp",1);
INSERT INTO images VALUES (3,"img2prod1","https://digitalbookinggruposseis.s3.amazonaws.com/products/product1/img2prod1.webp",1);
INSERT INTO images VALUES (4,"img3prod1","https://digitalbookinggruposseis.s3.amazonaws.com/products/product1/img3prod1.webp",1);
INSERT INTO images VALUES (5,"img4prod1","https://digitalbookinggruposseis.s3.amazonaws.com/products/product1/img4prod1.webp",1);
INSERT INTO images VALUES (6,"img5prod1","https://digitalbookinggruposseis.s3.amazonaws.com/products/product1/img5prod1.webp",1);
INSERT INTO images VALUES (7,"img6prod1","https://digitalbookinggruposseis.s3.amazonaws.com/products/product1/img6prod1.webp",1);
INSERT INTO images VALUES (8,"img7prod1","https://digitalbookinggruposseis.s3.amazonaws.com/products/product1/img7prod1.webp",1);
INSERT INTO images VALUES (9,"img8prod1","https://digitalbookinggruposseis.s3.amazonaws.com/products/product1/img8prod1.webp",1);
INSERT INTO images VALUES (10,"img10prod1","https://digitalbookinggruposseis.s3.amazonaws.com/products/product1/img1prod1.webp",1);
INSERT INTO images VALUES (20,"Portada2","https://digitalbookinggruposseis.s3.amazonaws.com/products/product2/portada2.webp",2);
INSERT INTO images VALUES (21,"img9prod2.webpa","https://digitalbookinggruposseis.s3.amazonaws.com/products/product2/img9prod2.webp",2);
INSERT INTO images VALUES (22,"img8prod2.webp","https://digitalbookinggruposseis.s3.amazonaws.com/products/product2/img8prod2.webp",2);
INSERT INTO images VALUES (23,"img7prod2.webp","https://digitalbookinggruposseis.s3.amazonaws.com/products/product2/img7prod2.webp",2);
INSERT INTO images VALUES (24,"img6prod2.webp","https://digitalbookinggruposseis.s3.amazonaws.com/products/product2/img6prod2.webp",2);
INSERT INTO images VALUES (25,"img5prod2.webp","https://digitalbookinggruposseis.s3.amazonaws.com/products/product2/img5prod2.webp",2);
INSERT INTO images VALUES (26,"img4prod2.webp","https://digitalbookinggruposseis.s3.amazonaws.com/products/product2/img4prod1.jpg",2);
INSERT INTO images VALUES (27,"img3prod2.webp","https://digitalbookinggruposseis.s3.amazonaws.com/products/product2/img3prod1.webp",2);
INSERT INTO images VALUES (28,"img2prod2.webp","https://digitalbookinggruposseis.s3.amazonaws.com/products/product2/img2prod2.jpg",2);
INSERT INTO images VALUES (29,"img1prod1.webp","https://digitalbookinggruposseis.s3.amazonaws.com/products/product2/img1prod2.webp",2);
INSERT INTO images VALUES (30,"Portada3","https://digitalbookinggruposseis.s3.amazonaws.com/products/product3/portada3.jpg",3);
INSERT INTO images VALUES (31,"img8prod3","https://digitalbookinggruposseis.s3.amazonaws.com/products/product3/img8prod3.jpg",3);
INSERT INTO images VALUES (32,"img7prod3","https://digitalbookinggruposseis.s3.amazonaws.com/products/product3/img7prod3.jpg",3);
INSERT INTO images VALUES (33,"img6prod3","https://digitalbookinggruposseis.s3.amazonaws.com/products/product3/img6prod3.jpg",3);
INSERT INTO images VALUES (34,"img5prod3","https://digitalbookinggruposseis.s3.amazonaws.com/products/product3/img5prod3.jpg",3);
INSERT INTO images VALUES (35,"img4prod3","https://digitalbookinggruposseis.s3.amazonaws.com/products/product3/img4prod3.jpg",3);
INSERT INTO images VALUES (36,"img3prod3","https://digitalbookinggruposseis.s3.amazonaws.com/products/product3/img3prod3.jpg",3);
INSERT INTO images VALUES (37,"img2prod3","https://digitalbookinggruposseis.s3.amazonaws.com/products/product3/img2prod3.jpg",3);
INSERT INTO images VALUES (38,"img1prod3","https://digitalbookinggruposseis.s3.amazonaws.com/products/product3/img1prod3.jpg",3);
INSERT INTO images VALUES (40,"Portada4","https://digitalbookinggruposseis.s3.amazonaws.com/products/product4/portada4.webp",4);
INSERT INTO images VALUES (41,"img8prod4.jpg","https://digitalbookinggruposseis.s3.amazonaws.com/products/product4/img8prod4.jpg",4);
INSERT INTO images VALUES (42,"img7prod4.wepg","https://digitalbookinggruposseis.s3.amazonaws.com/products/product4/img7prod4.webp",4);
INSERT INTO images VALUES (43,"img6prod4.jpg","https://digitalbookinggruposseis.s3.amazonaws.com/products/product4/img6prod4.jpg",4);
INSERT INTO images VALUES (44,"img5prod4.jpg","https://digitalbookinggruposseis.s3.amazonaws.com/products/product4/img5prod4.jpeg",4);
INSERT INTO images VALUES (45,"img4prod4.jpg","https://digitalbookinggruposseis.s3.amazonaws.com/products/product4/img4prod4.jpeg",4);
INSERT INTO images VALUES (46,"img3prod4.jpg","https://digitalbookinggruposseis.s3.amazonaws.com/products/product4/img3prod4.jpg",4);
INSERT INTO images VALUES (47,"img2prod4.jpg","https://digitalbookinggruposseis.s3.amazonaws.com/products/product4/img2prod4.jpg",4);
INSERT INTO images VALUES (48,"img1prod4.wepg","https://digitalbookinggruposseis.s3.amazonaws.com/products/product4/img1prod4.webp",4);
INSERT INTO images VALUES (50,"Portada5","https://digitalbookinggruposseis.s3.amazonaws.com/products/product5/portada5.jpg",5);
INSERT INTO images VALUES (51,"img7prod5","https://digitalbookinggruposseis.s3.amazonaws.com/products/product5/img7prod5.jpg",5);
INSERT INTO images VALUES (52,"img6prod5","https://digitalbookinggruposseis.s3.amazonaws.com/products/product5/img6prod5.jpg",5);
INSERT INTO images VALUES (53,"img5prod5","https://digitalbookinggruposseis.s3.amazonaws.com/products/product5/img5prod5.jpg",5);
INSERT INTO images VALUES (54,"img4prod5","https://digitalbookinggruposseis.s3.amazonaws.com/products/product5/img4prod5.jpg",5);
INSERT INTO images VALUES (55,"img3prod5","https://digitalbookinggruposseis.s3.amazonaws.com/products/product5/img3prod5.jpg",5);
INSERT INTO images VALUES (56,"img2prod5","https://digitalbookinggruposseis.s3.amazonaws.com/products/product5/img2prod5.jpg",5);
INSERT INTO images VALUES (57,"img1prod5","https://digitalbookinggruposseis.s3.amazonaws.com/products/product5/img1prod5.jpg",5);
INSERT INTO images VALUES (58,"portada6","https://digitalbookinggruposseis.s3.amazonaws.com/products/product6/portada6.webp",6);
INSERT INTO images VALUES (59,"img1prod6","https://digitalbookinggruposseis.s3.amazonaws.com/products/product6/img1prod6.webp",6);
INSERT INTO images VALUES (60,"img2prod6","https://digitalbookinggruposseis.s3.amazonaws.com/products/product6/img2prod6.webp",6);
INSERT INTO images VALUES (61,"img3prod6","https://digitalbookinggruposseis.s3.amazonaws.com/products/product6/img3prod6.webp",6);
INSERT INTO images VALUES (62,"img4prod6","https://digitalbookinggruposseis.s3.amazonaws.com/products/product6/img4prod6.webp",6);
INSERT INTO images VALUES (63,"img5prod6","https://digitalbookinggruposseis.s3.amazonaws.com/products/product6/img5prod6.webp",6);
INSERT INTO images VALUES (64,"img6prod6","https://digitalbookinggruposseis.s3.amazonaws.com/products/product6/img6prod6.webp",6);
INSERT INTO images VALUES (65,"portada7","https://digitalbookinggruposseis.s3.amazonaws.com/products/product7/portada7.jpg",7);
INSERT INTO images VALUES (66,"img1prod7","https://digitalbookinggruposseis.s3.amazonaws.com/products/product7/img1prod7.jpg",7);
INSERT INTO images VALUES (67,"img2prod7","https://digitalbookinggruposseis.s3.amazonaws.com/products/product7/img2prod7.jpg",7);
INSERT INTO images VALUES (68,"img3prod7","https://digitalbookinggruposseis.s3.amazonaws.com/products/product7/img3prod7.jpg",7);
INSERT INTO images VALUES (69,"img4prod7","https://digitalbookinggruposseis.s3.amazonaws.com/products/product7/img4prod7.jpg",7);
INSERT INTO images VALUES (70,"img5prod7","https://digitalbookinggruposseis.s3.amazonaws.com/products/product7/img5prod7.jpg",7);
INSERT INTO images VALUES (71,"img6prod7","https://digitalbookinggruposseis.s3.amazonaws.com/products/product7/img6prod7.jpg",7);
INSERT INTO images VALUES (72,"img7prod7","https://digitalbookinggruposseis.s3.amazonaws.com/products/product7/img7prod7.jpg",7);
INSERT INTO images VALUES (73,"portada8","https://digitalbookinggruposseis.s3.amazonaws.com/products/product8/portada8.jpg",8);
INSERT INTO images VALUES (74,"img1prod8","https://digitalbookinggruposseis.s3.amazonaws.com/products/product8/img1prod8.jpg",8);
INSERT INTO images VALUES (75,"img2prod8","https://digitalbookinggruposseis.s3.amazonaws.com/products/product8/img2prod8.webp",8);
INSERT INTO images VALUES (76,"img3prod8","https://digitalbookinggruposseis.s3.amazonaws.com/products/product8/img3prod8.webp",8);
INSERT INTO images VALUES (77,"img4prod8","https://digitalbookinggruposseis.s3.amazonaws.com/products/product8/img4prod8.webp",8);
INSERT INTO images VALUES (78,"img5prod8","https://digitalbookinggruposseis.s3.amazonaws.com/products/product8/img5prod8.webp",8);
INSERT INTO images VALUES (79,"img6prod8","https://digitalbookinggruposseis.s3.amazonaws.com/products/product8/img6prod8.jpg",8);
INSERT INTO images VALUES (80,"img7prod8","https://digitalbookinggruposseis.s3.amazonaws.com/products/product8/img7prod8.webp",8);
INSERT INTO users VALUES (1,"santi@digitalbooking.xyz","Garlot","Santiago","$2a$10$nozpu7y.IBSfRmvMolNoA..Xr056D20U/c34HhV4dW7R2GS6fbgCG");
INSERT INTO users VALUES (2,"jhon@digitalbooking.xyz","Parra","Jhon","$2a$10$WF4RqDZ9C8TFM6y7eq33OuRhZgFMkqrj2gq0/HJOcVeQE6UrlEkbm");
INSERT INTO users VALUES (3,"abril@digitalbooking.xyz","Santiso","Abril","$2a$10$q5571Slvs6CziTv/vhl9fOAE3byTgPdLSWDNt6Y2WGMLWP2TjAjQa");
INSERT INTO users VALUES (4,"sol@digitalbooking.xyz","Rocca","Soledad","$2a$10$3GOHfSq.rqkzP2YBAl17e.L1KnIyijAmCyqrIS.BwnkH4c0D9dHie");
INSERT INTO users VALUES (5,"dani@digitalbooking.xyz","Romero","Daniel","$2a$10$8e/xeExIef3FpVZHA6jLw.CS.vBTF4XVpVyoOIfVDf.T1AQbftcWa");
INSERT INTO users VALUES (6, "cristian@digitalbooking.xyz", "Sanchez", "Cristian", "$2a$10$RrmroYzYE04K5/HJdBVTteP7oTggneQMvB4qJeqyBk1Swqb8737J.");
INSERT INTO roles VALUES (1,"admin");
INSERT INTO roles VALUES (2,"user");
INSERT INTO user_rol VALUES (1,1);
INSERT INTO user_rol VALUES (2,1);
INSERT INTO user_rol VALUES (3,1);
INSERT INTO user_rol VALUES (4,1);
INSERT INTO user_rol VALUES (5,1);