select * from products;
select * from images;
select * from categories;
select * from cities;
select * from characteristics;
select * from users;
select * from reservations;
select * from roles; 
select * from user_rol; 